# Generated by Django 4.0.6 on 2022-10-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quicklab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practical',
            name='instructions',
        ),
        migrations.AlterField(
            model_name='practical',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('practical', models.ManyToManyField(related_name='instructions', to='Quicklab.practical')),
            ],
        ),
    ]
