# Generated by Django 4.0.6 on 2022-10-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quicklab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='title',
            new_name='instruction_title',
        ),
    ]
