# Generated by Django 4.0.6 on 2022-10-02 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quicklab', '0002_alter_practical_tools_alter_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='practicals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Teacher_practical', to='Quicklab.practical'),
        ),
    ]
