# Generated by Django 4.0.6 on 2022-10-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quicklab', '0003_teacher_practicals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practical',
            name='tools',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tool_practical', to='Quicklab.tool'),
        ),
        migrations.AlterField(
            model_name='student',
            name='no_of_practicals',
            field=models.IntegerField(default=0),
        ),
    ]
