# Generated by Django 4.1.1 on 2022-10-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quicklab', '0004_alter_practical_tools_alter_student_no_of_practicals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='practicals',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='student',
        ),
    ]
