# Generated by Django 4.1.1 on 2022-10-05 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quicklab', '0005_remove_teacher_practicals_remove_teacher_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='practicals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Teacher_practical', to='Quicklab.practical'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Teacher_student', to='Quicklab.student'),
        ),
    ]
